### ISSUE TITLE
Does this fork appropriately rotate 3D rotations?

### ISSUE THREAD

**Issue by GrantDare** [kylerlaird/advanced_navigation_driver#5]
Hi, I am experiencing an issue where I am traversing up a hill however the state estimate continually degrades in z (implying it's going down a hill). I just want to know if this branch correctly represents 3D movement?

**Comment by kylerlaird** [comment]
The orientation being wrong was the original reason that I forked this driver.  I recall testing it on a slight hill long ago but I can't say for certain that it's correct.  If it's backward it's fairly easy to fix.

**Comment by GrantDare** [comment]
@kylerlaird thanks for the prompt reply. Based on my testing I would say that the 3D rotation is incorrect, do you have a snippet or a source for me to modify it?

**Comment by kylerlaird** [comment]
In an_driver.cpp, at line 339, negate pitch.
-system_state_packet.orientation[1]

**Comment by GrantDare** [comment]
Thanks mate, after making this change I would consider this solved. I noticed no transform is required for angular velocities? Would I not have to also transform the angular velocities for the imu message?

**Comment by kylerlaird** [comment]
I suspect that it all needs to change.  I'm not in a position to do that right now.  I welcome patches.

**Comment by GrantDare** [comment]
Unfortunately, I don't have the time to test and refine the package at the moment either. Perhaps you should mark this as non conforming to [REP103](https://www.ros.org/reps/rep-0103.html). The support staff at advanced navigation directed me to your package when I asked about ENU.
